version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-dev
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client-dev
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    depends_on: 
      - web
    links: 
      - web
    environment:
      - NODE_ENV=development

  storybook:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: client-storybook
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '9009:9009'
    environment:
      - NODE_ENV=development
