version: '2'
services:
  web:
    build: .
    command: nodemon run start:server
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
     OPEN_SECRETS_KEY: 88d1aa9112f23c0bdf6a3fddaef2ccdf
