version: '3.7'

services:
  web:
    container_name: historyiswatching_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
  
  client:
    container_name: historyiswatching_client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: client-dev

    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    depends_on: 
      - web
    links: 
      - web
    environment:
      - NODE_ENV=development

  storybook:
    container_name: historyiswatching_storybook
    build:
      context: ./client
      dockerfile: Dockerfile
      target: client-storybook
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '9009:9009'
    environment:
      - NODE_ENV=development
