
const flat_ui = {
    turquoise: '#1ABC9C',
    'green-sea': '#16A085',
    emerald: '#2ECC71',
    nephritis: '#27AE60',
    'peter-river': '#3498DB',
    'belize-hole': '#2980B9',
    amethyst: '#9B59B6',
    wisteria: '#8E44AD',
    'wet-asphalt': '#34495E',
    'midnight-blue': '#2C3E50',
    'sun-flower': '#F1C40F',
    orange: '#F39C12',
    carrot: '#E67E22',
    pumpkin: '#D35400',
    alizarin: '#E74C3C',
    pomegranate: '#C0392B',
    clouds: '#ECF0F1',
    silver: '#BDC3C7',
    concrete: '#95A5A6',
    asbestos: '#7F8C8D',
};

export default {
  sky: '#b0e4ea',
  turquoise: flat_ui.turquoise,
  'turquoise-dark': flat_ui['green-sea'],
  green: flat_ui['emerald'],
  'green-dark': flat_ui['nephritis'],
  blue: flat_ui['peter-river'],
  'blue-dark': flat_ui['belize-hole'],
  purple: flat_ui['amethyst'],
  'purple-dark': flat_ui['wisteria'],
  navy: flat_ui['wet-asphalt'],
  'navy-dark': flat_ui['midnight-blue'],
  yellow: flat_ui['sun-flower'],
  'yellow-dark': flat_ui['orange'],
  orange: flat_ui['carrot'],
  'orange-dark': flat_ui['pumpkin'],
  red: flat_ui['alizarin'],
  'red-dark': flat_ui['pomegranate'],
  lightest: flat_ui['clouds'],
  light: flat_ui['silver'],
  gray: flat_ui['concrete'],
  'grey-dark': flat_ui['asbestos'],
};