export default [
  {
    code: 'A0000',
    name: 'Agriculture',
    catorder: 'A11',
    industry: 'Misc Agriculture',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A1000',
    name: 'Crop production & basic processing',
    catorder: 'A01',
    industry: 'Crop Production & Basic Processing',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A1100',
    name: 'Cotton',
    catorder: 'A01',
    industry: 'Crop Production & Basic Processing',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A1200',
    name: 'Sugar cane & sugar beets',
    catorder: 'A01',
    industry: 'Crop Production & Basic Processing',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A1300',
    name: 'Tobacco & Tobacco products',
    catorder: 'A02',
    industry: 'Tobacco',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A1400',
    name: 'Vegetables, fruits and tree nut',
    catorder: 'A01',
    industry: 'Crop Production & Basic Processing',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A1500',
    name: 'Wheat, corn, soybeans and cash grain',
    catorder: 'A01',
    industry: 'Crop Production & Basic Processing',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A1600',
    name: 'Other commodities (incl rice, peanuts, honey)',
    catorder: 'A01',
    industry: 'Crop Production & Basic Processing',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A2000',
    name: 'Milk & dairy producers',
    catorder: 'A04',
    industry: 'Dairy',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A2300',
    name: 'Poultry & eggs',
    catorder: 'A05',
    industry: 'Poultry & Eggs',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A3000',
    name: 'Livestock',
    catorder: 'A06',
    industry: 'Livestock',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A3100',
    name: 'Animal feed & health products',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A3200',
    name: 'Sheep and Wool Producers',
    catorder: 'A06',
    industry: 'Livestock',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A3300',
    name: 'Feedlots & related livestock services',
    catorder: 'A06',
    industry: 'Livestock',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A3500',
    name: 'Horse breeders',
    catorder: 'A06',
    industry: 'Livestock',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A4000',
    name: 'Agricultural services & related industries',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A4100',
    name: 'Agricultural chemicals (fertilizers & pesticides)',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A4200',
    name: 'Farm machinery & equipment',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A4300',
    name: 'Grain traders & terminals',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A4500',
    name: 'Veterinarians',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A5000',
    name: 'Forestry & Forest Products',
    catorder: 'A10',
    industry: 'Forestry & Forest Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A5200',
    name: 'Paper & pulp mills and paper manufacturing',
    catorder: 'A10',
    industry: 'Forestry & Forest Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A6000',
    name: 'Farm organizations & cooperatives',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A6500',
    name: 'Farm bureaus',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'A8000',
    name: 'Florists & Nursery Services',
    catorder: 'A07',
    industry: 'Agricultural Services/Products',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'B0000',
    name: 'Construction & Public Works',
    catorder: 'C01',
    industry: 'General Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B0500',
    name: 'Builders associations',
    catorder: 'C01',
    industry: 'General Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B1000',
    name: 'Public works, industrial & commercial construction',
    catorder: 'C01',
    industry: 'General Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B1200',
    name: 'Dredging Contractors',
    catorder: 'C01',
    industry: 'General Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B1500',
    name: 'Construction, unclassified',
    catorder: 'C01',
    industry: 'General Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B2000',
    name: 'Residential construction',
    catorder: 'C02',
    industry: 'Home Builders',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B2400',
    name: 'Mobile home construction',
    catorder: 'C02',
    industry: 'Home Builders',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B3000',
    name: 'Special trade contractors',
    catorder: 'C03',
    industry: 'Special Trade Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B3200',
    name: 'Electrical contractors',
    catorder: 'C03',
    industry: 'Special Trade Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B3400',
    name: 'Plumbing, heating & air conditioning',
    catorder: 'C03',
    industry: 'Special Trade Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B3600',
    name: 'Landscaping & Excavation Svcs',
    catorder: 'C03',
    industry: 'Special Trade Contractors',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B4000',
    name: 'Engineering, architecture & construction mgmt svcs',
    catorder: 'C04',
    industry: 'Construction Services',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B4200',
    name: 'Architectural services',
    catorder: 'C04',
    industry: 'Construction Services',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B4300',
    name: 'Surveying',
    catorder: 'C04',
    industry: 'Construction Services',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B4400',
    name: 'Engineers - type unknown',
    catorder: 'C04',
    industry: 'Construction Services',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B5000',
    name: 'Building materials',
    catorder: 'C05',
    industry: 'Building Materials & Equipment',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B5100',
    name: 'Stone, clay, glass & concrete products',
    catorder: 'C05',
    industry: 'Building Materials & Equipment',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B5200',
    name: 'Lumber and wood products',
    catorder: 'C05',
    industry: 'Building Materials & Equipment',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B5300',
    name: 'Plumbing & pipe products',
    catorder: 'C05',
    industry: 'Building Materials & Equipment',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B5400',
    name: 'Other construction-related products',
    catorder: 'C05',
    industry: 'Building Materials & Equipment',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B5500',
    name: 'Electrical Supply',
    catorder: 'C05',
    industry: 'Building Materials & Equipment',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'B6000',
    name: 'Construction equipment',
    catorder: 'C05',
    industry: 'Building Materials & Equipment',
    sector: 'Construction',
    sectorLong: 'Construction',
  },
  {
    code: 'C0000',
    name: 'Communications & Electronics',
    catorder: 'B00',
    industry: 'Misc Communications/Electronics',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C1000',
    name: 'Printing and publishing (printed & online)',
    catorder: 'B01',
    industry: 'Printing & Publishing',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C1100',
    name: 'Book, newspaper & periodical publishing',
    catorder: 'B01',
    industry: 'Printing & Publishing',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C1300',
    name: 'Commercial printing & typesetting',
    catorder: 'B01',
    industry: 'Printing & Publishing',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C1400',
    name: 'Greeting card publishing',
    catorder: 'B01',
    industry: 'Printing & Publishing',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2000',
    name: 'Entertainment industry/Broadcast & Motion Pictures',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2100',
    name: 'Commercial TV & radio stations',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2200',
    name: 'Cable & satellite TV production',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2300',
    name: 'TV production',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2400',
    name: 'Motion Picture production & distribution',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2600',
    name: 'Recorded Music & music production',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2700',
    name: 'Movie Theaters',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2800',
    name: 'Bands, orchestras & other live music production',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C2900',
    name: 'Live theater & other entertainment productions',
    catorder: 'B02',
    industry: 'TV/Movies/Music',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C4000',
    name: 'Telecommunications',
    catorder: 'B09',
    industry: 'Telecom Services',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C4100',
    name: 'Telephone utilities',
    catorder: 'B08',
    industry: 'Telephone Utilities',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C4200',
    name: 'Longdistance telephone & telegraph service',
    catorder: 'B08',
    industry: 'Telephone Utilities',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C4300',
    name: 'Cell/wireless service providers',
    catorder: 'B09',
    industry: 'Telecom Services',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C4400',
    name: 'Satellite communications',
    catorder: 'B09',
    industry: 'Telecom Services',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C4500',
    name: 'Cable distributors & service providers',
    catorder: 'B09',
    industry: 'Telecom Services',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C4600',
    name: 'Other Communications Services',
    catorder: 'B09',
    industry: 'Telecom Services',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C5000',
    name: 'Electronics manufacturing & services',
    catorder: 'B12',
    industry: 'Electronics Mfg & Equip',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C5100',
    name: 'Computer manufacture & services',
    catorder: 'B12',
    industry: 'Electronics Mfg & Equip',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C5110',
    name: 'Computer components & accessories',
    catorder: 'B12',
    industry: 'Electronics Mfg & Equip',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C5120',
    name: 'Computer software',
    catorder: 'B12',
    industry: 'Electronics Mfg & Equip',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C5130',
    name: 'Data processing & computer services',
    catorder: 'B12',
    industry: 'Electronics Mfg & Equip',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C5200',
    name: 'Telecommunications Devices',
    catorder: 'B12',
    industry: 'Electronics Mfg & Equip',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C5300',
    name: 'Other Communication Electronics',
    catorder: 'B12',
    industry: 'Electronics Mfg & Equip',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C5400',
    name: 'Industrial Electronics',
    catorder: 'B12',
    industry: 'Electronics Mfg & Equip',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C6000',
    name: 'Internet & Online Services',
    catorder: 'B13',
    industry: 'Internet',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C6100',
    name: 'Online Entertainment',
    catorder: 'B13',
    industry: 'Internet',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C6200',
    name: 'Social Media',
    catorder: 'B13',
    industry: 'Internet',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C6300',
    name: 'Search Engine/Email Services',
    catorder: 'B13',
    industry: 'Internet',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C6400',
    name: 'Vendors',
    catorder: 'B13',
    industry: 'Internet',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'C6500',
    name: 'Hosting/Cloud Services',
    catorder: 'B13',
    industry: 'Internet',
    sector: 'Communic/Electronics',
    sectorLong: 'Communications/Electronics',
  },
  {
    code: 'D0000',
    name: 'Defense',
    catorder: 'D03',
    industry: 'Misc Defense',
    sector: 'Defense',
    sectorLong: 'Defense',
  },
  {
    code: 'D2000',
    name: 'Defense aerospace contractors',
    catorder: 'D01',
    industry: 'Defense Aerospace',
    sector: 'Defense',
    sectorLong: 'Defense',
  },
  {
    code: 'D3000',
    name: 'Defense electronic contractors',
    catorder: 'D02',
    industry: 'Defense Electronics',
    sector: 'Defense',
    sectorLong: 'Defense',
  },
  {
    code: 'D4000',
    name: 'Defense Research & Development',
    catorder: 'D03',
    industry: 'Misc Defense',
    sector: 'Defense',
    sectorLong: 'Defense',
  },
  {
    code: 'D5000',
    name: 'Defense shipbuilders',
    catorder: 'D03',
    industry: 'Misc Defense',
    sector: 'Defense',
    sectorLong: 'Defense',
  },
  {
    code: 'D6000',
    name: 'Homeland Security contractors',
    catorder: 'D03',
    industry: 'Misc Defense',
    sector: 'Defense',
    sectorLong: 'Defense',
  },
  {
    code: 'D8000',
    name: 'Ground-based & other weapons systems',
    catorder: 'D03',
    industry: 'Misc Defense',
    sector: 'Defense',
    sectorLong: 'Defense',
  },
  {
    code: 'D9000',
    name: 'Defense-related services',
    catorder: 'D03',
    industry: 'Misc Defense',
    sector: 'Defense',
    sectorLong: 'Defense',
  },
  {
    code: 'E0000',
    name: 'Energy, Natural Resources and Environment',
    catorder: 'E07',
    industry: 'Misc Energy',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1000',
    name: 'Energy production & distribution',
    catorder: 'E07',
    industry: 'Misc Energy',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1100',
    name: 'Oil & Gas',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1110',
    name: 'Major (multinational) oil & gas producers',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1120',
    name: 'Independent oil & gas producers',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1140',
    name: 'Natural Gas transmission & distribution',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1150',
    name: 'Oilfield service, equipment & exploration',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1160',
    name: 'Petroleum refining & marketing',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1170',
    name: 'Gasoline service stations',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1180',
    name: 'Fuel oil dealers',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1190',
    name: 'LPG/Liquid Propane dealers & producers',
    catorder: 'E01',
    industry: 'Oil & Gas',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1200',
    name: 'Mining',
    catorder: 'E04',
    industry: 'Mining',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1210',
    name: 'Coal mining',
    catorder: 'E04',
    industry: 'Mining',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1220',
    name: 'Metal mining & processing',
    catorder: 'E04',
    industry: 'Mining',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1230',
    name: 'Non-metallic mining',
    catorder: 'E04',
    industry: 'Mining',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1240',
    name: 'Mining services & equipment',
    catorder: 'E04',
    industry: 'Mining',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1300',
    name: 'Nuclear energy',
    catorder: 'E08',
    industry: 'Electric Utilities',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1320',
    name: 'Nuclear plant construction, equipment & svcs',
    catorder: 'E08',
    industry: 'Electric Utilities',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1500',
    name: 'Alternate energy production & services',
    catorder: 'E07',
    industry: 'Misc Energy',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1600',
    name: 'Electric Power utilities',
    catorder: 'E08',
    industry: 'Electric Utilities',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1610',
    name: 'Rural electric cooperatives',
    catorder: 'E08',
    industry: 'Electric Utilities',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1620',
    name: 'Gas & Electric Utilities',
    catorder: 'E08',
    industry: 'Electric Utilities',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1630',
    name: 'Independent power generation & cogeneration',
    catorder: 'E08',
    industry: 'Electric Utilities',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E1700',
    name: 'Power plant construction & equipment',
    catorder: 'E07',
    industry: 'Misc Energy',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E2000',
    name: 'Environmental services, equipment & consulting',
    catorder: 'E09',
    industry: 'Environmental Svcs/Equipment',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E3000',
    name: 'Waste management',
    catorder: 'E10',
    industry: 'Waste Management',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E4000',
    name: 'Fisheries & wildlife',
    catorder: 'E11',
    industry: 'Fisheries & Wildlife',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E4100',
    name: 'Fishing',
    catorder: 'E11',
    industry: 'Fisheries & Wildlife',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E4200',
    name: 'Hunting & wildlife',
    catorder: 'E11',
    industry: 'Fisheries & Wildlife',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'E5000',
    name: 'Water Utilities',
    catorder: 'E07',
    industry: 'Misc Energy',
    sector: 'Energy/Nat Resource',
    sectorLong: 'Energy & Natural Resources',
  },
  {
    code: 'F0000',
    name: 'Finance, Insurance & Real Estate',
    catorder: 'F13',
    industry: 'Misc Finance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F1000',
    name: 'Banks & lending institutions',
    catorder: 'F03',
    industry: 'Commercial Banks',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F1100',
    name: 'Commercial banks & bank holding companies',
    catorder: 'F03',
    industry: 'Commercial Banks',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F1200',
    name: 'Savings banks & Savings and Loans',
    catorder: 'F04',
    industry: 'Savings & Loans',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F1300',
    name: 'Credit unions',
    catorder: 'F05',
    industry: 'Credit Unions',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F1400',
    name: 'Credit agencies & finance companies',
    catorder: 'F06',
    industry: 'Finance/Credit Companies',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F1410',
    name: 'Student loan companies',
    catorder: 'F06',
    industry: 'Finance/Credit Companies',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F1420',
    name: 'Payday lenders',
    catorder: 'F06',
    industry: 'Finance/Credit Companies',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2000',
    name: 'Securities, commodities & investment',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2100',
    name: 'Security brokers & investment companies',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2110',
    name: 'Discount & Online Brokers',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2200',
    name: 'Commodity brokers/dealers',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2300',
    name: 'Investment banking',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2400',
    name: 'Stock exchanges',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2500',
    name: 'Venture capital',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2600',
    name: 'Private Equity & Investment Firms',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F2700',
    name: 'Hedge Funds',
    catorder: 'F07',
    industry: 'Securities & Investment',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F3000',
    name: 'Insurance',
    catorder: 'F09',
    industry: 'Insurance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F3100',
    name: 'Insurance companies, brokers & agents',
    catorder: 'F09',
    industry: 'Insurance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F3200',
    name: 'Accident & health insurance',
    catorder: 'F09',
    industry: 'Insurance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F3300',
    name: 'Life insurance',
    catorder: 'F09',
    industry: 'Insurance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F3400',
    name: 'Property & casualty insurance',
    catorder: 'F09',
    industry: 'Insurance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F4000',
    name: 'Real estate',
    catorder: 'F10',
    industry: 'Real Estate',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F4100',
    name: 'Real Estate developers & subdividers',
    catorder: 'F10',
    industry: 'Real Estate',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F4200',
    name: 'Real estate agents',
    catorder: 'F10',
    industry: 'Real Estate',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F4300',
    name: 'Title insurance & title abstract offices',
    catorder: 'F10',
    industry: 'Real Estate',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F4400',
    name: 'Mobile home dealers & parks',
    catorder: 'F10',
    industry: 'Real Estate',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F4500',
    name: 'Building operators and managers',
    catorder: 'F10',
    industry: 'Real Estate',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F4600',
    name: 'Mortgage bankers and brokers',
    catorder: 'F10',
    industry: 'Real Estate',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F4700',
    name: 'Other real estate services',
    catorder: 'F10',
    industry: 'Real Estate',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F5000',
    name: 'Financial services & consulting',
    catorder: 'F13',
    industry: 'Misc Finance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F5100',
    name: 'Accountants',
    catorder: 'F11',
    industry: 'Accountants',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F5200',
    name: 'Credit reporting services & collection agencies',
    catorder: 'F13',
    industry: 'Misc Finance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F5300',
    name: 'Tax return services',
    catorder: 'F13',
    industry: 'Misc Finance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F5500',
    name: 'Other financial services',
    catorder: 'F13',
    industry: 'Misc Finance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'F7000',
    name: 'Investors',
    catorder: 'F13',
    industry: 'Misc Finance',
    sector: 'Finance/Insur/RealEst',
    sectorLong: 'Finance, Insurance & Real Estate',
  },
  {
    code: 'G0000',
    name: 'General commerce',
    catorder: 'N12',
    industry: 'Misc Business',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G1000',
    name: 'General business associations',
    catorder: 'N00',
    industry: 'Business Associations',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G1100',
    name: 'Chambers of commerce',
    catorder: 'N00',
    industry: 'Business Associations',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G1200',
    name: 'Small business associations',
    catorder: 'N00',
    industry: 'Business Associations',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G1300',
    name: 'Pro-business associations',
    catorder: 'N00',
    industry: 'Business Associations',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G1310',
    name: 'Business tax coalitions',
    catorder: 'N00',
    industry: 'Business Associations',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G1400',
    name: 'International trade associations',
    catorder: 'N00',
    industry: 'Business Associations',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2000',
    name: 'Food & Beverage Products and Services',
    catorder: 'A09',
    industry: 'Food Processing & Sales',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'G2100',
    name: 'Food and kindred products manufacturing',
    catorder: 'A09',
    industry: 'Food Processing & Sales',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'G2110',
    name: 'Artificial sweeteners and food additives',
    catorder: 'N01',
    industry: 'Food & Beverage',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2200',
    name: 'Confectionery processors & manufacturers',
    catorder: 'N01',
    industry: 'Food & Beverage',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2300',
    name: 'Meat processing & products',
    catorder: 'A09',
    industry: 'Food Processing & Sales',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'G2350',
    name: 'Fish Processing',
    catorder: 'N01',
    industry: 'Food & Beverage',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2400',
    name: 'Food stores',
    catorder: 'A09',
    industry: 'Food Processing & Sales',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'G2500',
    name: 'Food wholesalers',
    catorder: 'A09',
    industry: 'Food Processing & Sales',
    sector: 'Agribusiness',
    sectorLong: 'Agribusiness',
  },
  {
    code: 'G2600',
    name: 'Beverages (non-alcoholic)',
    catorder: 'N01',
    industry: 'Food & Beverage',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2700',
    name: 'Beverage bottling & distribution',
    catorder: 'N01',
    industry: 'Food & Beverage',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2800',
    name: 'Alcohol',
    catorder: 'N02',
    industry: 'Beer, Wine & Liquor',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2810',
    name: 'Beer',
    catorder: 'N02',
    industry: 'Beer, Wine & Liquor',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2820',
    name: 'Wine & distilled spirits manufacturing',
    catorder: 'N02',
    industry: 'Beer, Wine & Liquor',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2840',
    name: 'Liquor stores',
    catorder: 'N02',
    industry: 'Beer, Wine & Liquor',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2850',
    name: 'Liquor wholesalers',
    catorder: 'N02',
    industry: 'Beer, Wine & Liquor',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2860',
    name: 'Marijuana Production, Sales & Paraphernalia',
    catorder: 'N09',
    industry: 'Marijuana',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2900',
    name: 'Restaurants & drinking establishments',
    catorder: 'N01',
    industry: 'Food & Beverage',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G2910',
    name: 'Food catering & food services',
    catorder: 'N01',
    industry: 'Food & Beverage',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G3000',
    name: 'Wholesale trade',
    catorder: 'N12',
    industry: 'Misc Business',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G3500',
    name: 'Import/Export services',
    catorder: 'N12',
    industry: 'Misc Business',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4000',
    name: 'Retail trade',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4100',
    name: 'Apparel & accessory stores',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4200',
    name: 'Consumer electronics & computer stores',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4300',
    name: 'Department, variety & convenience stores',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4400',
    name: 'Furniture & appliance stores',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4500',
    name: 'Hardware & building materials stores',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4600',
    name: 'Miscellaneous retail stores',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4700',
    name: 'Catalog & mail order houses',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4800',
    name: 'Direct sales',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4850',
    name: 'Vending Machine Sales & Services',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G4900',
    name: 'Drug stores',
    catorder: 'N03',
    industry: 'Retail Sales',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5000',
    name: 'Services',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5100',
    name: 'Beauty & barber shops',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5200',
    name: 'Business services',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5210',
    name: 'Advertising & public relations services',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5220',
    name: 'Direct mail advertising services',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5230',
    name: 'Outdoor advertising services',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5240',
    name: 'Commercial photography, art & graphic design',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5250',
    name: 'Employment agencies',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5260',
    name: 'Political consultants/advisers',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5270',
    name: 'Management consultants & services',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5280',
    name: 'Marketing research services',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5290',
    name: 'Security services',
    catorder: 'N05',
    industry: 'Business Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5300',
    name: 'Equipment rental & leasing',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5400',
    name: 'Funeral services',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5500',
    name: 'Laundries & dry cleaners',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5600',
    name: 'Miscellaneous repair services',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5700',
    name: 'Pest control',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G5800',
    name: 'Physical fitness centers',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G6000',
    name: 'Recreation/Entertainment',
    catorder: 'N06',
    industry: 'Recreation/Live Entertainment',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G6100',
    name: 'Amusement/recreation centers',
    catorder: 'N06',
    industry: 'Recreation/Live Entertainment',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G6400',
    name: 'Professional sports, arenas & related equip & svcs',
    catorder: 'N06',
    industry: 'Recreation/Live Entertainment',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G6500',
    name: 'Casinos, racetracks & gambling',
    catorder: 'N07',
    industry: 'Casinos/Gambling',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G6550',
    name: 'Indian Gaming',
    catorder: 'N07',
    industry: 'Casinos/Gambling',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G6700',
    name: 'Amusement parks',
    catorder: 'N06',
    industry: 'Recreation/Live Entertainment',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G6800',
    name: 'Video rental',
    catorder: 'N04',
    industry: 'Misc Services',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'G7000',
    name: 'Correctional facilities constr & mgmt/for-profit',
    catorder: 'N12',
    industry: 'Misc Business',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'H0000',
    name: 'Health, Education & Human Resources',
    catorder: 'H05',
    industry: 'Misc Health',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1000',
    name: 'Health professionals',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1100',
    name: 'Physicians',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1110',
    name: 'Psychiatrists & psychologists',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1120',
    name: 'Optometrists & Ophthalmologists',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1130',
    name: 'Other physician specialists',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1400',
    name: 'Dentists',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1500',
    name: 'Chiropractors',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1700',
    name: 'Other non-physician health practitioners',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1710',
    name: 'Nurses',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H1750',
    name: 'Pharmacists',
    catorder: 'H01',
    industry: 'Health Professionals',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H2000',
    name: 'Health care institutions',
    catorder: 'H02',
    industry: 'Hospitals/Nursing Homes',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H2100',
    name: 'Hospitals',
    catorder: 'H02',
    industry: 'Hospitals/Nursing Homes',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H2200',
    name: 'Nursing homes',
    catorder: 'H02',
    industry: 'Hospitals/Nursing Homes',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H2300',
    name: 'Drug & alcohol treatment hospitals',
    catorder: 'H02',
    industry: 'Hospitals/Nursing Homes',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3000',
    name: 'Health care services',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3100',
    name: 'Home care services',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3200',
    name: 'Outpatient health services (incl drug & alcohol)',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3300',
    name: 'Optical services (glasses & contact lenses)',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3400',
    name: 'Medical laboratories',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3500',
    name: 'AIDS treatment & testing',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3700',
    name: 'HMOs',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3800',
    name: 'Mental Health Services',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H3900',
    name: 'Health care Consultants',
    catorder: 'H03',
    industry: 'Health Services/HMOs',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H4000',
    name: 'Health care products',
    catorder: 'H04',
    industry: 'Pharmaceuticals/Health Products',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H4100',
    name: 'Medical Devices & Supplies',
    catorder: 'H04',
    industry: 'Pharmaceuticals/Health Products',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H4200',
    name: 'Personal health care products',
    catorder: 'H04',
    industry: 'Pharmaceuticals/Health Products',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H4300',
    name: 'Pharmaceutical manufacturing',
    catorder: 'H04',
    industry: 'Pharmaceuticals/Health Products',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H4400',
    name: 'Pharmaceutical wholesale',
    catorder: 'H04',
    industry: 'Pharmaceuticals/Health Products',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H4500',
    name: 'Biotech products & research',
    catorder: 'H04',
    industry: 'Pharmaceuticals/Health Products',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H4600',
    name: 'Nutritional & dietary supplements',
    catorder: 'H04',
    industry: 'Pharmaceuticals/Health Products',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H4700',
    name: 'Pharmaceutical cannabis',
    catorder: 'H04',
    industry: 'Pharmaceuticals/Health Products',
    sector: 'Health',
    sectorLong: 'Health',
  },
  {
    code: 'H5000',
    name: 'Education',
    catorder: 'W04',
    industry: 'Education',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'H5100',
    name: 'Schools & colleges',
    catorder: 'W04',
    industry: 'Education',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'H5150',
    name: 'Medical schools',
    catorder: 'W04',
    industry: 'Education',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'H5170',
    name: 'Law schools',
    catorder: 'W04',
    industry: 'Education',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'H5200',
    name: 'Technical, business and vocational schools & svcs',
    catorder: 'W04',
    industry: 'Education',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'H5300',
    name: 'For-profit Education',
    catorder: 'W04',
    industry: 'Education',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'H6000',
    name: 'Welfare & Social Work',
    catorder: 'W07',
    industry: 'Other',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'J0000',
    name: 'Ideological & Single Issue PACs',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J1000',
    name: 'General Ideological',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J1100',
    name: 'Republican/Conservative',
    catorder: 'Q01',
    industry: 'Republican/Conservative',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J1110',
    name: 'Christian Conservative',
    catorder: 'Q01',
    industry: 'Republican/Conservative',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J1200',
    name: 'Democratic/Liberal',
    catorder: 'Q02',
    industry: 'Democratic/Liberal',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J1300',
    name: 'Third-party committees',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J2000',
    name: 'Leadership committees',
    catorder: 'Q03',
    industry: 'Leadership PACs',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J2100',
    name: 'Democratic leadership PAC',
    catorder: 'Q03',
    industry: 'Leadership PACs',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J2200',
    name: 'Republican leadership PAC',
    catorder: 'Q03',
    industry: 'Leadership PACs',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J2300',
    name: 'Democratic officials, candidates & former members',
    catorder: 'Q03',
    industry: 'Leadership PACs',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J2400',
    name: 'Republican officials, candidates & former members',
    catorder: 'Q03',
    industry: 'Leadership PACs',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J2500',
    name: 'Non-Federal candidate committees',
    catorder: 'Q03',
    industry: 'Leadership PACs',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J3000',
    name: 'Consumer groups',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J4000',
    name: 'Fiscal & tax policy',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J5000',
    name: 'Foreign policy',
    catorder: 'Q04',
    industry: 'Foreign & Defense Policy',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J5100',
    name: 'Pro-Israel',
    catorder: 'Q05',
    industry: 'Pro-Israel',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J5200',
    name: 'Anti-Castro',
    catorder: 'Q04',
    industry: 'Foreign & Defense Policy',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J5300',
    name: 'Puerto Rico statehood policy',
    catorder: 'Q04',
    industry: 'Foreign & Defense Policy',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J5400',
    name: 'Pro-Arab',
    catorder: 'Q04',
    industry: 'Foreign & Defense Policy',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J6100',
    name: 'Anti-Guns',
    catorder: 'Q12',
    industry: 'Gun Control',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J6200',
    name: 'Pro-Guns',
    catorder: 'Q13',
    industry: 'Gun Rights',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J6500',
    name: 'Militias & Anti-Government Groups',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7000',
    name: 'Human Rights',
    catorder: 'Q09',
    industry: 'Human Rights',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7120',
    name: 'Abortion policy/Anti-Abortion',
    catorder: 'Q14',
    industry: 'Abortion Policy/Anti-Abortion',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7150',
    name: 'Abortion policy/Pro-Abortion Rights',
    catorder: 'Q15',
    industry: 'Abortion Policy/Pro-Abortion Rights',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7200',
    name: 'Elderly issues/Social Security',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7210',
    name: 'Legalization of Doctor-Assisted Suicide',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7300',
    name: 'Gay & lesbian rights & issues',
    catorder: 'Q09',
    industry: 'Human Rights',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7400',
    name: 'Women\'s issues',
    catorder: 'Q08',
    industry: 'Women\'s Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7500',
    name: 'Minority/Ethnic Groups',
    catorder: 'Q09',
    industry: 'Human Rights',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7510',
    name: 'Native American Tribes',
    catorder: 'Q09',
    industry: 'Human Rights',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7600',
    name: 'Animal Rights',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J7700',
    name: 'Children\'s rights',
    catorder: 'Q09',
    industry: 'Human Rights',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J8000',
    name: 'Labor, anti-union',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J9000',
    name: 'Other single-issue or ideological groups',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'J9100',
    name: 'Term limits',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'JD100',
    name: 'Defense policy, hawks',
    catorder: 'Q04',
    industry: 'Foreign & Defense Policy',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'JD200',
    name: 'Defense policy, doves',
    catorder: 'Q04',
    industry: 'Foreign & Defense Policy',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'JE300',
    name: 'Environmental policy',
    catorder: 'Q11',
    industry: 'Environment',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'JH100',
    name: 'Health & welfare policy',
    catorder: 'Q09',
    industry: 'Human Rights',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'JW100',
    name: 'Pro-resource development groups',
    catorder: 'Q10',
    industry: 'Misc Issues',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'K0000',
    name: 'Legal Services',
    catorder: 'K01',
    industry: 'Lawyers/Law Firms',
    sector: 'Lawyers & Lobbyists',
    sectorLong: 'Lawyers & Lobbyists',
  },
  {
    code: 'K1000',
    name: 'Attorneys & law firms',
    catorder: 'K01',
    industry: 'Lawyers/Law Firms',
    sector: 'Lawyers & Lobbyists',
    sectorLong: 'Lawyers & Lobbyists',
  },
  {
    code: 'K1100',
    name: 'Trial lawyers & law firms',
    catorder: 'K01',
    industry: 'Lawyers/Law Firms',
    sector: 'Lawyers & Lobbyists',
    sectorLong: 'Lawyers & Lobbyists',
  },
  {
    code: 'K1200',
    name: 'Corporate lawyers & law firms',
    catorder: 'K01',
    industry: 'Lawyers/Law Firms',
    sector: 'Lawyers & Lobbyists',
    sectorLong: 'Lawyers & Lobbyists',
  },
  {
    code: 'K2000',
    name: 'Lobbyists & Public Relations',
    catorder: 'K02',
    industry: 'Lobbyists',
    sector: 'Lawyers & Lobbyists',
    sectorLong: 'Lawyers & Lobbyists',
  },
  {
    code: 'K2100',
    name: 'Registered Foreign Agents',
    catorder: 'K02',
    industry: 'Lobbyists',
    sector: 'Lawyers & Lobbyists',
    sectorLong: 'Lawyers & Lobbyists',
  },
  {
    code: 'L0000',
    name: 'Labor Unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'L1000',
    name: 'Civil service & government unions',
    catorder: 'P04',
    industry: 'Public sector Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'L1100',
    name: 'Federal employees unions',
    catorder: 'P04',
    industry: 'Public sector Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'L1200',
    name: 'State & local govt employee unions',
    catorder: 'P04',
    industry: 'Public sector Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'L1300',
    name: 'Teachers unions',
    catorder: 'P04',
    industry: 'Public sector Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'L1400',
    name: 'Police & firefighters unions & associations',
    catorder: 'P04',
    industry: 'Public sector Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'L1500',
    name: 'US Postal Service unions & associations',
    catorder: 'P04',
    industry: 'Public sector Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'L5000',
    name: 'Other unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LA100',
    name: 'Agricultural labor unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LB100',
    name: 'Building trades unions',
    catorder: 'P01',
    industry: 'Building Trade Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LC100',
    name: 'Communications & hi-tech unions',
    catorder: 'P02',
    industry: 'Industrial Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LC150',
    name: 'IBEW (Intl Brotherhood of Electrical Workers)',
    catorder: 'P02',
    industry: 'Industrial Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LD100',
    name: 'Defense-related unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LE100',
    name: 'Mining unions',
    catorder: 'P02',
    industry: 'Industrial Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LE200',
    name: 'Energy-related unions (non-mining)',
    catorder: 'P02',
    industry: 'Industrial Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LG000',
    name: 'General commercial unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LG100',
    name: 'Food service & related unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LG200',
    name: 'Retail trade unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LG300',
    name: 'Commercial service unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LG400',
    name: 'Entertainment unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LG500',
    name: 'Other commercial unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LH100',
    name: 'Health worker unions',
    catorder: 'P05',
    industry: 'Misc Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LM100',
    name: 'Manufacturing unions',
    catorder: 'P02',
    industry: 'Industrial Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LM150',
    name: 'Automotive Manufacturing union',
    catorder: 'P02',
    industry: 'Industrial Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LT000',
    name: 'Transportation unions',
    catorder: 'P03',
    industry: 'Transportation Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LT100',
    name: 'Air transport unions',
    catorder: 'P03',
    industry: 'Transportation Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LT300',
    name: 'Teamsters union',
    catorder: 'P03',
    industry: 'Transportation Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LT400',
    name: 'Railroad unions',
    catorder: 'P03',
    industry: 'Transportation Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LT500',
    ame: 'Merchant marine &_longhoremen unions',
    catorder: 'P03',
    industry: 'Transportation Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'LT600',
    name: 'Other transportation unions',
    catorder: 'P03',
    industry: 'Transportation Unions',
    sector: 'Labor',
    sectorLong: 'Labor',
  },
  {
    code: 'M0000',
    name: 'Manufacturing',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M1000',
    name: 'Chemicals',
    catorder: 'N13',
    industry: 'Chemical & Related Manufacturing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M1100',
    name: 'Explosives',
    catorder: 'N13',
    industry: 'Chemical & Related Manufacturing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M1300',
    name: 'Household cleansers & chemicals',
    catorder: 'N13',
    industry: 'Chemical & Related Manufacturing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M1400',
    name: 'Manmade fibers',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M1500',
    name: 'Plastics & Rubber processing & products',
    catorder: 'N13',
    industry: 'Chemical & Related Manufacturing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M1600',
    name: 'Paints, Solvents & Coatings',
    catorder: 'N13',
    industry: 'Chemical & Related Manufacturing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M1700',
    name: 'Adhesives & Sealants',
    catorder: 'N13',
    industry: 'Chemical & Related Manufacturing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M2000',
    name: 'Heavy industrial manufacturing',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M2100',
    name: 'Steel',
    catorder: 'N14',
    industry: 'Steel Production',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M2200',
    name: 'Smelting & non-petroleum refining',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M2250',
    name: 'Aluminum mining/processing',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M2300',
    name: 'Industrial/commercial equipment & materials',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M2400',
    name: 'Recycling of metal, paper, plastics, etc.',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M3000',
    name: 'Personal products manufacturing',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M3100',
    name: 'Clothing & accessories',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M3200',
    name: 'Shoes & leather products',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M3300',
    name: 'Toiletries & cosmetics',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M3400',
    name: 'Jewelry',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M3500',
    name: 'Toys',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M3600',
    name: 'Sporting goods sales & manufacturing',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M4000',
    name: 'Household & office products',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M4100',
    name: 'Furniture & wood products',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M4200',
    name: 'Office machines',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M4300',
    name: 'Household appliances',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M5000',
    name: 'Fabricated metal products',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M5100',
    name: 'Hardware & tools',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M5200',
    name: 'Electroplating, polishing & related services',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M5300',
    name: 'Small arms & ammunition',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M6000',
    name: 'Electrical lighting products',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M7000',
    name: 'Paper, glass & packaging materials',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M7100',
    name: 'Paper packaging materials',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M7200',
    name: 'Glass products',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M7300',
    name: 'Metal cans & containers',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M8000',
    name: 'Textiles & fabrics',
    catorder: 'N16',
    industry: 'Textiles',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M9000',
    name: 'Precision instruments',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M9100',
    name: 'Optical instruments & lenses',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M9200',
    name: 'Photographic equipment & supplies',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'M9300',
    name: 'Clocks & watches',
    catorder: 'N15',
    industry: 'Misc Manufacturing & Distributing',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'T0000',
    name: 'Transportation',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T1000',
    name: 'Air transport',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T1100',
    name: 'Airlines',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T1200',
    name: 'Aircraft manufacturers',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T1300',
    name: 'Aircraft parts & equipment',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T1400',
    name: 'General aviation (private pilots)',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T1500',
    name: 'Air freight',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T1600',
    name: 'Aviation services & airports',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T1700',
    name: 'Space vehicles & components',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T2000',
    name: 'Automotive, Misc',
    catorder: 'M02',
    industry: 'Automotive',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T2100',
    name: 'Auto manufacturers',
    catorder: 'M02',
    industry: 'Automotive',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T2200',
    name: 'Truck/Automotive parts & accessories',
    catorder: 'M02',
    industry: 'Automotive',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T2300',
    name: 'Auto dealers, new & used',
    catorder: 'M02',
    industry: 'Automotive',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T2310',
    name: 'Auto dealers, foreign imports',
    catorder: 'M02',
    industry: 'Automotive',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T2400',
    name: 'Auto repair',
    catorder: 'M02',
    industry: 'Automotive',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T2500',
    name: 'Car rental agencies',
    catorder: 'M02',
    industry: 'Automotive',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T3000',
    name: 'Trucking',
    catorder: 'M03',
    industry: 'Trucking',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T3100',
    name: 'Trucking companies & services',
    catorder: 'M03',
    industry: 'Trucking',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T3200',
    name: 'Truck & trailer manufacturers',
    catorder: 'M03',
    industry: 'Trucking',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T4000',
    name: 'Buses & Taxis',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T4100',
    name: 'Bus services',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T4200',
    name: 'Taxicabs',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T5000',
    name: 'Railroad transportation',
    catorder: 'M04',
    industry: 'Railroads',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T5100',
    name: 'Railroads',
    catorder: 'M04',
    industry: 'Railroads',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T5200',
    name: 'Manufacturers of railroad equipment',
    catorder: 'M04',
    industry: 'Railroads',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T5300',
    name: 'Railroad services',
    catorder: 'M04',
    industry: 'Railroads',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T6000',
    name: 'Sea transport',
    catorder: 'M05',
    industry: 'Sea Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T6100',
    name: 'Ship building & repair',
    catorder: 'M05',
    industry: 'Sea Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T6200',
    name: 'Sea freight & passenger services',
    catorder: 'M05',
    industry: 'Sea Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T6250',
    name: 'Cruise ships & lines',
    catorder: 'M05',
    industry: 'Sea Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T7000',
    name: 'Freight & delivery services',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T7100',
    name: 'Express delivery services',
    catorder: 'M01',
    industry: 'Air Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T7200',
    name: 'Warehousing',
    catorder: 'N12',
    industry: 'Misc Business',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'T8000',
    name: 'Recreational transport',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T8100',
    name: 'Motorcycles, snowmobiles & other motorized vehicle',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T8200',
    name: 'Motor homes & camper trailers',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T8300',
    name: 'Pleasure boats',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T8400',
    name: 'Bicycles & other non-motorized recreational transp',
    catorder: 'M06',
    industry: 'Misc Transport',
    sector: 'Transportation',
    sectorLong: 'Transportation',
  },
  {
    code: 'T9000',
    name: 'Lodging & tourism',
    catorder: 'N08',
    industry: 'Lodging/Tourism',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'T9100',
    name: 'Hotels & motels',
    catorder: 'N08',
    industry: 'Lodging/Tourism',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'T9300',
    name: 'Resorts',
    catorder: 'N08',
    industry: 'Lodging/Tourism',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'T9400',
    name: 'Travel agents',
    catorder: 'N08',
    industry: 'Lodging/Tourism',
    sector: 'Misc Business',
    sectorLong: 'Misc Business',
  },
  {
    code: 'X0000',
    name: 'Other',
    catorder: 'W07',
    industry: 'Other',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X1200',
    name: 'Retired',
    catorder: 'W06',
    industry: 'Retired',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X3000',
    name: 'Civil servant/public employee',
    catorder: 'W03',
    industry: 'Civil Servants/Public Officials',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X3100',
    name: 'Public official (elected or appointed)',
    catorder: 'W03',
    industry: 'Civil Servants/Public Officials',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X3200',
    name: 'Courts & Justice System',
    catorder: 'W03',
    industry: 'Civil Servants/Public Officials',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X3300',
    name: 'Municipal & county government organizations',
    catorder: 'W03',
    industry: 'Civil Servants/Public Officials',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X3500',
    name: 'Public school teachers, administrators & officials',
    catorder: 'W04',
    industry: 'Education',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X3700',
    name: 'US Postal Service',
    catorder: 'W03',
    industry: 'Civil Servants/Public Officials',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X4000',
    name: 'Non-Profits',
    catorder: 'W02',
    industry: 'Non-Profit Institutions',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X4100',
    name: 'Non-profit foundations',
    catorder: 'W02',
    industry: 'Non-Profit Institutions',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X4110',
    name: 'Philanthropists',
    catorder: 'W02',
    industry: 'Non-Profit Institutions',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X4200',
    name: 'Museums, art galleries, libraries, etc.',
    catorder: 'W02',
    industry: 'Non-Profit Institutions',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X5000',
    name: 'Military',
    catorder: 'W07',
    industry: 'Other',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X7000',
    name: 'Churches, clergy & religious organizations',
    catorder: 'W05',
    industry: 'Clergy & Religious Organizations',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X8000',
    name: 'International Organizations',
    catorder: 'W07',
    industry: 'Other',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'X9000',
    name: 'Foreign Governments',
    catorder: 'W07',
    industry: 'Other',
    sector: 'Other',
    sectorLong: 'Other',
  },
  {
    code: 'Y0000',
    name: 'Unknown',
    catorder: 'Y00',
    industry: 'Unknown',
    sector: 'Unknown',
    sectorLong: 'Unknown',
  },
  {
    code: 'Y1000',
    name: 'Homemakers, students & other non-income earners',
    catorder: 'Y01',
    industry: 'Homemakers/Non-income earners',
    sector: 'Unknown',
    sectorLong: 'Unknown',
  },
  {
    code: 'Y2000',
    name: 'No employer listed or discovered',
    catorder: 'Y02',
    industry: 'No Employer Listed or Found',
    sector: 'Unknown',
    sectorLong: 'Unknown',
  },
  {
    code: 'Y3000',
    name: 'Generic occupation - impossible to assign category',
    catorder: 'Y03',
    industry: 'Generic Occupation/Category Unknown',
    sector: 'Unknown',
    sectorLong: 'Unknown',
  },
  {
    code: 'Y4000',
    name: 'Employer listed but category unknown',
    catorder: 'Y04',
    industry: 'Employer Listed/Category Unknown',
    sector: 'Unknown',
    sectorLong: 'Unknown',
  },
  {
    code: 'Z1000',
    name: 'Candidate Committees',
    catorder: 'Q16',
    industry: 'Candidate Committees',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'Z1100',
    name: 'Republican Candidate Committees',
    catorder: 'Q16',
    industry: 'Candidate Committees',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'Z1200',
    name: 'Democratic Candidate Committees',
    catorder: 'Q16',
    industry: 'Candidate Committees',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'Z1300',
    name: 'Third-Party Candidate Committees',
    catorder: 'Q16',
    industry: 'Candidate Committees',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'Z1400',
    name: 'Unknown-Party Candidate Committees',
    catorder: 'Q16',
    industry: 'Candidate Committees',
    sector: 'Ideology/Single-Issue',
    sectorLong: 'Ideological/Single-Issue',
  },
  {
    code: 'Z4100',
    name: 'Republican Joint Candidate Committee',
    catorder: 'Z04',
    industry: 'Joint Candidate Cmte',
    sector: 'Joint Candidate Cmtes',
    sectorLong: 'Joint Candidate Cmtes',
  },
  {
    code: 'Z4200',
    name: 'Democratic Joint Candidate Committee',
    catorder: 'Z04',
    industry: 'Joint Candidate Cmte',
    sector: 'Joint Candidate Cmtes',
    sectorLong: 'Joint Candidate Cmtes',
  },
  {
    code: 'Z4300',
    name: 'Third-Party Joint Candidate Committee',
    catorder: 'Z04',
    industry: 'Joint Candidate Cmte',
    sector: 'Joint Candidate Cmtes',
    sectorLong: 'Joint Candidate Cmtes',
  },
  {
    code: 'Z4400',
    name: 'Liberal Non-party Joint Fundraising Committee',
    catorder: 'Z04',
    industry: 'Joint Candidate Cmte',
    sector: 'Joint Candidate Cmtes',
    sectorLong: 'Joint Candidate Cmtes',
  },
  {
    code: 'Z4500',
    name: 'Conservative Non-party Joint Fundraising Committee',
    catorder: 'Z04',
    industry: 'Joint Candidate Cmte',
    sector: 'Joint Candidate Cmtes',
    sectorLong: 'Joint Candidate Cmtes',
  },
  {
    code: 'Z5000',
    name: 'Party Committees',
    catorder: 'Z02',
    industry: 'Party Committees',
    sector: 'Party Cmte',
    sectorLong: 'Party Cmtes',
  },
  {
    code: 'Z5100',
    name: 'Republican Party Committees',
    catorder: 'Z02',
    industry: 'Party Committees',
    sector: 'Party Cmte',
    sectorLong: 'Party Cmtes',
  },
  {
    code: 'Z5200',
    name: 'Democratic Party Committees',
    catorder: 'Z02',
    industry: 'Party Committees',
    sector: 'Party Cmte',
    sectorLong: 'Party Cmtes',
  },
  {
    code: 'Z5300',
    name: 'Third-Party Party Committees',
    catorder: 'Z02',
    industry: 'Party Committees',
    sector: 'Party Cmte',
    sectorLong: 'Party Cmtes',
  },
  {
    code: 'Z9000',
    name: 'Candidate contribution to his/her own campaign',
    catorder: 'Z07',
    industry: 'Candidate Self-finance',
    sector: 'Candidate',
    sectorLong: 'Candidate',
  },
  {
    code: 'Z9100',
    name: 'Transfer between national party committees',
    catorder: 'Z08',
    industry: 'Party Committee Transfer',
    sector: 'Non-contribution',
    sectorLong: 'Non-contribution',
  },
  {
    code: 'Z9500',
    name: 'Transfer from intermediary (type 24I or 24T)',
    catorder: 'Z09',
    industry: 'Non-contribution',
    sector: 'Non-contribution',
    sectorLong: 'Non-contribution',
  },
  {
    code: 'Z9600',
    name: 'Non-Contribution, Miscellaneous',
    catorder: 'Z09',
    industry: 'Non-contribution',
    sector: 'Non-contribution',
    sectorLong: 'Non-contribution',
  },
  {
    code: 'Z9700',
    name: 'Unitemized (small) contributions',
    catorder: 'Z09',
    industry: 'Non-contribution',
    sector: 'Non-contribution',
    sectorLong: 'Non-contribution',
  },
  {
    code: 'Z9800',
    name: 'Public Funding',
    catorder: 'Z09',
    industry: 'Non-contribution',
    sector: 'Non-contribution',
    sectorLong: 'Non-contribution',
  },
  {
    code: 'Z9999',
    name: 'Internal Transfer and other non-contributions',
    catorder: 'Z09',
    industry: 'Non-contribution',
    sector: 'Non-contribution',
    sectorLong: 'Non-contribution',
  },
];
