const RESPONSE = {
  state: 'CA',
  timestamp: '2019-11-06T00:56:52.919Z',
  reps: [
    {
      cid: 'N00033987',
      firstlast: 'Doug LaMalfa',
      lastname: 'LAMALFA',
      party: 'R',
      office: 'CA01',
      gender: 'M',
      first_elected: '2012',
      exit_code: '0',
      comments: '',
      phone: '202-225-3076',
      fax: '530-534-7800',
      website: 'http://lamalfa.house.gov',
      webform: 'https://lamalfa.house.gov/contact/email-me',
      congress_office: '322 Cannon House Office Building',
      bioguide_id: 'L000578',
      votesmart_id: '29713',
      feccandid: 'H2CA02142',
      twitter_id: 'RepLaMalfa',
      youtube_url: 'https://youtube.com/RepLaMalfa',
      facebook_id: 'RepLaMalfa',
      birthdate: '1960-07-02',
    },

    {
      cid: 'N00033030',
      firstlast: 'Jared Huffman',
      lastname: 'HUFFMAN',
      party: 'D',
      office: 'CA02',
      gender: 'M',
      first_elected: '2012',
      exit_code: '0',
      comments: '',
      phone: '202-225-5161',
      fax: '202-225-5163',
      website: 'http://huffman.house.gov',
      webform: 'https://huffman.house.gov/contact/email-me',
      congress_office: '1406 Longworth House Office Building',
      bioguide_id: 'H001068',
      votesmart_id: '59849',
      feccandid: 'H2CA06259',
      twitter_id: 'RepHuffman',
      youtube_url: 'https://youtube.com/rephuffman',
      facebook_id: 'RepHuffman',
      birthdate: '1964-02-18',
    },

    {
      cid: 'N00030856',
      firstlast: 'John Garamendi',
      lastname: 'GARAMENDI',
      party: 'D',
      office: 'CA03',
      gender: 'M',
      first_elected: '2009',
      exit_code: '0',
      comments: '',
      phone: '202-225-1880',
      fax: '202-225-5914',
      website: 'http://garamendi.house.gov',
      webform: 'https://garamendi.house.gov/contact-me/email-me',
      congress_office: '2438 Rayburn House Office Building',
      bioguide_id: 'G000559',
      votesmart_id: '29664',
      feccandid: 'H0CA10149',
      twitter_id: 'RepGaramendi',
      youtube_url: 'https://youtube.com/garamendiCA10',
      facebook_id: 'repgaramendi',
      birthdate: '1945-01-24',
    },

    {
      cid: 'N00006863',
      firstlast: 'Tom McClintock',
      lastname: 'MCCLINTOCK',
      party: 'R',
      office: 'CA04',
      gender: 'M',
      first_elected: '2008',
      exit_code: '0',
      comments: '',
      phone: '202-225-2511',
      fax: '202-225-5444',
      website: 'http://mcclintock.house.gov',
      webform: 'https://mcclintockforms.house.gov/forms/contact-form.shtml',
      congress_office: '2312 Rayburn House Office Building',
      bioguide_id: 'M001177',
      votesmart_id: '9715',
      feccandid: 'H8CA04152',
      twitter_id: 'RepMcClintock',
      youtube_url: 'https://youtube.com/McClintockCA04',
      facebook_id: 'Congressman-Tom-McClintock-81125319109',
      birthdate: '1956-07-10',
    },

    {
      cid: 'N00007419',
      firstlast: 'Mike Thompson',
      lastname: 'THOMPSON',
      party: 'D',
      office: 'CA05',
      gender: 'M',
      first_elected: '1998',
      exit_code: '0',
      comments: '',
      phone: '202-225-3311',
      fax: '202-225-4335',
      website: 'http://mikethompson.house.gov',
      webform: 'https://mikethompson.house.gov/contact/email-me',
      congress_office: '231 Cannon House Office Building',
      bioguide_id: 'T000460',
      votesmart_id: '3564',
      feccandid: 'H8CA01109',
      twitter_id: 'RepThompson',
      youtube_url: 'https://youtube.com/CongressmanMThompson',
      facebook_id: 'RepMikeThompson',
      birthdate: '1951-01-24',
    },

    {
      cid: 'N00027459',
      firstlast: 'Doris O Matsui',
      lastname: 'MATSUI',
      party: 'D',
      office: 'CA06',
      gender: 'F',
      first_elected: '2005',
      exit_code: '0',
      comments: '',
      phone: '202-225-7163',
      fax: '202-225-0566',
      website: 'https://matsui.house.gov',
      webform: 'https://matsui.house.gov/email-representative-matsui',
      congress_office: '2311 Rayburn House Office Building',
      bioguide_id: 'M001163',
      votesmart_id: '28593',
      feccandid: 'H6CA05195',
      twitter_id: 'DorisMatsui',
      youtube_url: 'https://youtube.com/RepDorisMatsui',
      facebook_id: 'doris.matsui',
      birthdate: '1944-09-25',
    },

    {
      cid: 'N00030717',
      firstlast: 'Ami Bera',
      lastname: 'BERA',
      party: 'D',
      office: 'CA07',
      gender: 'M',
      first_elected: '2012',
      exit_code: '0',
      comments: '',
      phone: '202-225-5716',
      fax: '202-226-1298',
      website: 'http://bera.house.gov',
      webform: 'https://beraforms.house.gov/forms/writeyourrep/',
      congress_office: '1431 Longworth House Office Building',
      bioguide_id: 'B001287',
      votesmart_id: '120030',
      feccandid: 'H0CA03078',
      twitter_id: 'RepBera',
      youtube_url: 'https://youtube.com/repamibera',
      facebook_id: 'RepAmiBera',
      birthdate: '1965-03-02',
    },

    {
      cid: 'N00034224',
      firstlast: 'Paul Cook',
      lastname: 'COOK',
      party: 'R',
      office: 'CA08',
      gender: 'M',
      first_elected: '2012',
      exit_code: '0',
      comments: '',
      phone: '202-225-5861',
      fax: '202-225-6498',
      website: 'http://cook.house.gov',
      webform: 'https://cook.house.gov/contact/email-me',
      congress_office: '1222 Longworth House Office Building',
      bioguide_id: 'C001094',
      votesmart_id: '58121',
      feccandid: 'H2CA08164',
      twitter_id: 'RepPaulCook',
      youtube_url: 'https://youtube.com/RepPaulCook',
      facebook_id: 'RepPaulCook',
      birthdate: '1943-03-03',
    },

    {
      cid: 'N00026926',
      firstlast: 'Jerry McNerney',
      lastname: 'MCNERNY',
      party: 'D',
      office: 'CA09',
      gender: 'M',
      first_elected: '2006',
      exit_code: '0',
      comments: '',
      phone: '202-225-1947',
      fax: '202-225-4060',
      website: 'http://mcnerney.house.gov',
      webform: 'https://mcnerney.house.gov/contact/email-me',
      congress_office: '2265 Rayburn House Office Building',
      bioguide_id: 'M001166',
      votesmart_id: '29474',
      feccandid: 'H4CA11081',
      twitter_id: 'RepMcNerney',
      youtube_url: 'https://youtube.com/RepJerryMcNerney',
      facebook_id: 'jerrymcnerney',
      birthdate: '1951-06-18',
    },

    {
      cid: 'N00031593',
      firstlast: 'Jeff Denham',
      lastname: 'DENHAM',
      party: 'R',
      office: 'CA10',
      gender: 'M',
      first_elected: '2010',
      exit_code: '21',
      comments: 'Lost general election',
      phone: '202-225-4540',
      fax: '202-225-3402',
      website: 'http://denham.house.gov',
      webform: 'https://denham.house.gov/contact-me/email-me',
      congress_office: '1730 Longworth House Office Building',
      bioguide_id: 'D000612',
      votesmart_id: '28769',
      feccandid: 'H0CA19173',
      twitter_id: 'RepJeffDenham',
      youtube_url: 'https://youtube.com/repjeffdenham',
      facebook_id: 'RepJeffDenham',
      birthdate: '1967-07-29',
    },

    {
      cid: 'N00030709',
      firstlast: 'Mark Desaulnier',
      lastname: 'DESAULNIER',
      party: 'D',
      office: 'CA11',
      gender: 'M',
      first_elected: '2014',
      exit_code: '0',
      comments: '',
      phone: '202-225-2095',
      fax: '202-225-5609',
      website: 'https://desaulnier.house.gov',
      webform: '',
      congress_office: '115 Cannon House Office Building',
      bioguide_id: 'D000623',
      votesmart_id: '',
      feccandid: 'H0CA10073',
      twitter_id: 'RepDeSaulnier',
      youtube_url: '',
      facebook_id: 'RepMarkDeSaulnier',
      birthdate: '1952-03-31',
    },

    {
      cid: 'N00007360',
      firstlast: 'Nancy Pelosi',
      lastname: 'PELOSI',
      party: 'D',
      office: 'CA12',
      gender: 'F',
      first_elected: '1987',
      exit_code: '0',
      comments: '',
      phone: '202-225-4965',
      fax: '202-225-8259',
      website: 'http://pelosi.house.gov',
      webform: 'http://pelosi.house.gov/contact-me/email-me',
      congress_office: '233 Cannon House Office Building',
      bioguide_id: 'P000197',
      votesmart_id: '26732',
      feccandid: 'H8CA05035',
      twitter_id: 'NancyPelosi',
      youtube_url: 'https://youtube.com/nancypelosi',
      facebook_id: 'NancyPelosi',
      birthdate: '1940-03-26',
    },

    {
      cid: 'N00008046',
      firstlast: 'Barbara Lee',
      lastname: 'LEE',
      party: 'D',
      office: 'CA13',
      gender: 'F',
      first_elected: '1998',
      exit_code: '0',
      comments: '',
      phone: '202-225-2661',
      fax: '202-225-9817',
      website: 'https://lee.house.gov',
      webform: 'http://lee.house.gov/contact-the-office/email-me',
      congress_office: '2267 Rayburn House Office Building',
      bioguide_id: 'L000551',
      votesmart_id: '8315',
      feccandid: 'H8CA09060',
      twitter_id: 'RepBarbaraLee',
      youtube_url: 'https://youtube.com/RepLee',
      facebook_id: 'RepBarbaraLee',
      birthdate: '1946-07-16',
    },

    {
      cid: 'N00029649',
      firstlast: 'Jackie Speier',
      lastname: 'SPEIER',
      party: 'D',
      office: 'CA14',
      gender: 'F',
      first_elected: '2008',
      exit_code: '0',
      comments: '',
      phone: '202-225-3531',
      fax: '202-347-0956',
      website: 'https://speier.house.gov',
      webform: 'https://forms.house.gov/speier/webforms/email_jackie.shtml',
      congress_office: '2465 Rayburn House Office Building',
      bioguide_id: 'S001175',
      votesmart_id: '8425',
      feccandid: 'H8CA12171',
      twitter_id: 'RepSpeier',
      youtube_url: 'https://youtube.com/jackiespeierca12',
      facebook_id: 'JackieSpeier',
      birthdate: '1950-05-14',
    },

    {
      cid: 'N00033508',
      firstlast: 'Eric Swalwell',
      lastname: 'SWALWELL',
      party: 'D',
      office: 'CA15',
      gender: 'M',
      first_elected: '2012',
      exit_code: '0',
      comments: '',
      phone: '202-225-5065',
      fax: '',
      website: 'https://swalwell.house.gov',
      webform: 'http://swalwell.house.gov/contact-me/email-eric/',
      congress_office: '129 Cannon House Office Building',
      bioguide_id: 'S001193',
      votesmart_id: '129529',
      feccandid: 'H2CA15094',
      twitter_id: 'RepSwalwell',
      youtube_url: 'https://youtube.com/ericswalwell',
      facebook_id: 'CongressmanEricSwalwell',
      birthdate: '1980-11-16',
    },

    {
      cid: 'N00026341',
      firstlast: 'Jim Costa',
      lastname: 'COSTA',
      party: 'D',
      office: 'CA16',
      gender: 'M',
      first_elected: '2004',
      exit_code: '0',
      comments: '',
      phone: '202-225-3341',
      fax: '202-225-9308',
      website: 'https://costa.house.gov',
      webform: 'http://www.house.gov/formcosta/issue.htm',
      congress_office: '2081 Rayburn House Office Building',
      bioguide_id: 'C001059',
      votesmart_id: '3577',
      feccandid: 'H4CA20082',
      twitter_id: 'RepJimCosta',
      youtube_url: 'https://youtube.com/RepJimCostaCA20',
      facebook_id: 'RepJimCosta',
      birthdate: '1952-04-13',
    },

    {
      cid: 'N00026427',
      firstlast: 'Ro Khanna',
      lastname: 'KHANNA',
      party: 'D',
      office: 'CA17',
      gender: 'M',
      first_elected: '2016',
      exit_code: '0',
      comments: '',
      phone: '202-225-2631',
      fax: '',
      website: 'https://khanna.house.gov',
      webform: '',
      congress_office: '513 Cannon House Office Building',
      bioguide_id: 'K000389',
      votesmart_id: '',
      feccandid: '',
      twitter_id: 'RepRoKhanna',
      youtube_url: '',
      facebook_id: 'RepRoKhanna',
      birthdate: '1976-09-13',
    },

    {
      cid: 'N00007335',
      firstlast: 'Anna Eshoo',
      lastname: 'ESHOO',
      party: 'D',
      office: 'CA18',
      gender: 'F',
      first_elected: '1992',
      exit_code: '0',
      comments: '',
      phone: '202-225-8104',
      fax: '202-225-8890',
      website: 'http://eshoo.house.gov',
      webform: 'https://eshoo.house.gov/email-me/',
      congress_office: '241 Cannon House Office Building',
      bioguide_id: 'E000215',
      votesmart_id: '26741',
      feccandid: 'H8CA12098',
      twitter_id: 'RepAnnaEshoo',
      youtube_url: 'https://youtube.com/RepAnnaEshoo',
      facebook_id: 'RepAnnaEshoo',
      birthdate: '1942-12-13',
    },

    {
      cid: 'N00007479',
      firstlast: 'Zoe Lofgren',
      lastname: 'LOFGREN',
      party: 'D',
      office: 'CA19',
      gender: 'F',
      first_elected: '1994',
      exit_code: '0',
      comments: '',
      phone: '202-225-3072',
      fax: '202-225-3336',
      website: 'https://lofgren.house.gov',
      webform: 'http://lofgren.house.gov/contact/',
      congress_office: '1401 Longworth House Office Building',
      bioguide_id: 'L000397',
      votesmart_id: '21899',
      feccandid: 'H4CA16049',
      twitter_id: 'RepZoeLofgren',
      youtube_url: 'https://youtube.com/RepZoeLofgren',
      facebook_id: 'zoelofgren',
      birthdate: '1947-12-21',
    },

    {
      cid: 'N00038601',
      firstlast: 'Jimmy Panetta',
      lastname: 'PANETTA',
      party: 'D',
      office: 'CA20',
      gender: 'M',
      first_elected: '2016',
      exit_code: '0',
      comments: '',
      phone: '202-225-2861',
      fax: '',
      website: 'https://panetta.house.gov',
      webform: '',
      congress_office: '228 Cannon House Office Building',
      bioguide_id: 'P000613',
      votesmart_id: '',
      feccandid: '',
      twitter_id: 'RepJimmyPanetta',
      youtube_url: '',
      facebook_id: 'RepJimmyPanetta',
      birthdate: '1969-10-01',
    },

    {
      cid: 'N00033367',
      firstlast: 'David Valadao',
      lastname: 'VALADAO',
      party: 'R',
      office: 'CA21',
      gender: 'M',
      first_elected: '2012',
      exit_code: '0',
      comments: '',
      phone: '202-225-4695',
      fax: '202-226-3196',
      website: 'http://valadao.house.gov',
      webform: 'http://valadao.house.gov/contact/',
      congress_office: '1728 Longworth House Office Building',
      bioguide_id: 'V000129',
      votesmart_id: '120200',
      feccandid: 'H2CA20094',
      twitter_id: 'RepDavidValadao',
      youtube_url: 'https://youtube.com/congressmanvaladao',
      facebook_id: 'CongressmanDavidValadao',
      birthdate: '1977-04-14',
    },

    {
      cid: 'N00007248',
      firstlast: 'Devin Nunes',
      lastname: 'NUNES',
      party: 'R',
      office: 'CA22',
      gender: 'M',
      first_elected: '2002',
      exit_code: '0',
      comments: '',
      phone: '202-225-2523',
      fax: '202-225-3404',
      website: 'http://nunes.house.gov',
      webform: 'https://nunes.house.gov/contactform/default.aspx',
      congress_office: '1013 Longworth House Office Building',
      bioguide_id: 'N000181',
      votesmart_id: '16725',
      feccandid: 'H8CA20059',
      twitter_id: 'Rep_DevinNunes',
      youtube_url: 'https://youtube.com/RepDevinNunes',
      facebook_id: 'Congressman-Devin-Nunes-376470350795',
      birthdate: '1973-10-01',
    },

    {
      cid: 'N00028152',
      firstlast: 'Kevin McCarthy',
      lastname: 'MCCARTHY',
      party: 'R',
      office: 'CA23',
      gender: 'M',
      first_elected: '2006',
      exit_code: '0',
      comments: '',
      phone: '202-225-2915',
      fax: '202-225-2908',
      website: 'http://kevinmccarthy.house.gov',
      webform: 'https://kevinmccarthy.house.gov/contact/email-me',
      congress_office: '2421 Rayburn House Office Building',
      bioguide_id: 'M001165',
      votesmart_id: '28918',
      feccandid: 'H6CA22125',
      twitter_id: 'GOPLeader',
      youtube_url: 'https://youtube.com/repkevinmccarthy',
      facebook_id: 'CongressmanKevinMcCarthy',
      birthdate: '1965-01-26',
    },
  ],
};


export default RESPONSE